version: '3.6'

services:

  movies:
    build:
      context: ./services/movies
      dockerfile: Dockerfile
    volumes:
      - './services/movies:/opt/app'
    expose:
      - 3031

  nginx:
    build: .
    ports:
      - 80:80
    depends_on:
      - movies

networks:
  default:
    external:
      name: library
