version: '3.6'

services:

  movies:
    build:
      context: ./services/movies
      dockerfile: Dockerfile
    volumes:
      - './services/movies:/opt/app'
    expose:
      - 3031

  # library:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - './frontend:/opt/app'

  nginx:
    build: .
    ports:
      - 80:80
    depends_on:
      - movies

networks:
  default:
    external:
      name: library
